language: python
dist: trusty

python:
  - '3.6'
  - 'nightly'

sudo: false

cache: pip

install:
  - pip install --requirement requirements.txt
  - pip install pylint

script:
  - pylint duckduckgo

notifications:
  email:
    on_success: change
    on_failure: always
